### ISSUE TITLE
NNUE file

### ISSUE THREAD

**Issue by gabrielp10031978** [rn5f107s2/Molybdenum#97]
Hello,
I didn't find the NNUE file, please help me.
Thanks.

**Comment by gabrielp10031978** [comment]
The NNUE file should be in the same folder with the .exe file, right?

**Comment by rn5f107s2** [comment]
If you are running an .exe you dont need to worry about the NNUE file, it is already be built into the .exe file, so there is no need for putting the NNUE file in a specific folder
